Wip master
learn-co-curriculum/react-unidirectional-data-lab pull request #1
Opened 2016-09-29 21:55 UTC by alexanderGugel

Let's build a note taking app! Thoughts?

2016-10-04 07:51 UTC, thomastuts requested changes
Looks great! Some minor grammar nits, but that's it.

I also noticed the images are missing (the `assets/` directory and its corresponding images are not checked into the repo yet). Could you fix that too?

2016-10-04 07:51 UTC, thomastuts commented on README.md
> +This is how it's going to look like:
How it's going to look / What it's going to look like

2016-10-04 07:51 UTC, thomastuts commented on README.md
> +buttons. When a user click on the "Add note" button, a new file is being added
is ~~being~~ added

2016-10-04 07:51 UTC, thomastuts commented on README.md
> +There should always be at least one file in the sidebar. If the user attempts to
I like this gotcha! Nice way to spice things up a little. 💣

2016-10-04 07:55 UTC, thomastuts commented on package.json
> +    "classnames": "^2.2.5",
`sinon` is missing here

2016-10-04 08:00 UTC, thomastuts commented on components/Toolbar.js
> +class Toolbar extends React.Component {
This can be a stateless functional component

2016-10-05 00:38 UTC, alexanderGugel commented on README.md
> +This is how it's going to look like:
I always get that one wrong....

2016-10-05 00:42 UTC, alexanderGugel commented
@thomastuts Done! Thanks!

2016-10-05 04:44 UTC, thomastuts commented
@alexanderGugel Yep! I'll let you pull the switch 😄

2016-10-05 23:06 UTC, merged