Wip solution
learn-co-curriculum/react-unidirectional-data-lab pull request #2
Opened 2016-09-29 21:56 UTC by alexanderGugel

2016-10-04 08:01 UTC, thomastuts requested changes
Some minor code nits here, but nothing too big. Could we also add a line after every method in a class to improve code readability a little? I feel like the component code is pretty dense now.

2016-10-04 08:01 UTC, thomastuts commented on components/Sidebar.js
> +    const { files, selectedFileIndex, onAdd } = this.props;
`onAdd` isn't being used anywhere

2016-10-04 08:01 UTC, thomastuts commented on components/Sidebar.js
> +          ))
Missing semicolon

2016-10-04 08:01 UTC, thomastuts commented on components/App.js
> +    ev.preventDefault()
Missing semicolon

2016-10-04 08:01 UTC, thomastuts commented on components/SidebarItem.js
> +  static getTitle (file) {
While I like the use of a static method here, most students won't know what this is. I think we can extract this logic out into a function completely separate from the React component? (We can still keep it in the same file)

2016-10-04 08:01 UTC, thomastuts commented on components/SidebarItem.js
> +          {title ? title : <em>Untitled</em>}
I think we can simplify this to `{title || <em>Untitled</em>}`

2016-10-05 00:44 UTC, alexanderGugel commented on components/Sidebar.js
> +          ))
Hmmm..... Don't think so

2016-10-05 00:50 UTC, alexanderGugel commented
@thomastuts Done! Ready to merge?

2016-10-05 04:43 UTC, thomastuts commented on components/Sidebar.js
> +          ))
Ah, sorry, you're absolutely right - this is an expression. Not sure how I missed that. Scratch that!

2016-10-05 04:44 UTC, thomastuts commented
@alexanderGugel Yep! I'll let you pull the switch 😄

2016-10-05 23:06 UTC, merged